brew 'awscli'
brew 'bash-completion'
brew 'codefresh'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'docker-credential-helper'
brew 'docker-machine-completion'
brew 'git'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'nvm'
brew 'rbenv'
brew 'redis', restart_service: :changed
brew 'watch'
brew 'yq'

cask 'aws-vault'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
